-- ============================================================
-- Show Me The Money — Supabase 外部接口資料快取表
-- ------------------------------------------------------------
-- 本腳本為 idempotent（可重複執行），建立本專案所有對外 API
-- 的資料表 + RLS + 索引。資料表都是「公用快取」：
--   - 任何使用者（含匿名）皆可 SELECT
--   - 僅已登入使用者可 INSERT / UPDATE（避免匿名濫寫）
-- 使用方式：
--   1. 至 Supabase Dashboard → SQL Editor
--   2. 新建 query，貼上整份內容後按「Run」
--   3. 執行結果應看到「Success. No rows returned」
-- ============================================================

-- ============================================================
-- 1. 通用 API 快取（key/value 式，存任何 endpoint 的原始回應）
-- ============================================================
create table if not exists public.api_cache (
  id          bigint generated by default as identity primary key,
  source      text  not null,          -- 'twse'|'tpex'|'taifex'|'yf'|'goodinfo'|'reddit'|'ptt'|'udn'|'gnews'|'ndc'|'gtranslate'
  endpoint    text  not null,          -- normalized key，如 'T86:20260423'、'yfChart:2330.TW:1y'
  payload     jsonb not null,
  fetched_at  timestamptz not null default now(),
  ttl_seconds int   not null default 3600,
  expires_at  timestamptz
              generated always as
              (fetched_at + make_interval(secs => ttl_seconds)) stored,
  unique (source, endpoint)
);
create index if not exists idx_api_cache_source  on public.api_cache(source);
create index if not exists idx_api_cache_expires on public.api_cache(expires_at);


-- ============================================================
-- 2. 大盤指數 / 期貨（TAIEX、OTC、TXF、TXF_NIGHT）
-- ============================================================
create table if not exists public.market_indices (
  trade_date  date   not null,
  symbol      text   not null,         -- 'TAIEX','OTC','TXF','TXF_NIGHT'
  price       numeric(14,4),
  change      numeric(14,4),
  change_pct  numeric(8,4),
  volume_lots bigint,
  raw         jsonb,
  updated_at  timestamptz not null default now(),
  primary key (trade_date, symbol)
);
create index if not exists idx_market_indices_symbol on public.market_indices(symbol);


-- ============================================================
-- 3. 個股歷史日 K（TWSE STOCK_DAY + TPEX 合併）
-- ============================================================
create table if not exists public.stock_daily (
  trade_date  date   not null,
  stock_code  text   not null,
  open        numeric(12,4),
  high        numeric(12,4),
  low         numeric(12,4),
  close       numeric(12,4),
  volume      bigint,
  change      numeric(12,4),
  change_pct  numeric(8,4),
  source      text,                    -- 'twse' | 'tpex' | 'yf'
  raw         jsonb,
  updated_at  timestamptz not null default now(),
  primary key (trade_date, stock_code)
);
create index if not exists idx_stock_daily_code on public.stock_daily(stock_code);
create index if not exists idx_stock_daily_date on public.stock_daily(trade_date desc);


-- ============================================================
-- 4. 個股即時報價（MIS / TPEX）— 覆蓋式
-- ============================================================
create table if not exists public.stock_quotes (
  stock_code  text primary key,
  price       numeric(12,4),
  prev_close  numeric(12,4),
  change      numeric(12,4),
  change_pct  numeric(8,4),
  volume      bigint,
  market      text,                    -- 'tse' | 'otc'
  fetched_at  timestamptz not null default now(),
  raw         jsonb
);
create index if not exists idx_stock_quotes_fetched on public.stock_quotes(fetched_at desc);


-- ============================================================
-- 5. 個股基本面（Goodinfo 擷取）
-- ============================================================
create table if not exists public.stock_fundamentals (
  stock_code       text primary key,
  pe               numeric(10,4),
  dividend_yield   numeric(8,4),
  last_price       numeric(12,4),
  last_change_pct  numeric(8,4),
  source_url       text,
  fetched_at       timestamptz not null default now(),
  raw              jsonb
);


-- ============================================================
-- 6. 法人籌碼（TWSE T86 個股級）
-- ============================================================
create table if not exists public.institutional_flow (
  trade_date  date not null,
  stock_code  text not null,
  foreign_net bigint,                  -- 外陸資淨買賣（張）
  trust_net   bigint,                  -- 投信
  dealer_net  bigint,                  -- 自營商合計
  raw         jsonb,
  updated_at  timestamptz not null default now(),
  primary key (trade_date, stock_code)
);
create index if not exists idx_inst_flow_code on public.institutional_flow(stock_code);
create index if not exists idx_inst_flow_date on public.institutional_flow(trade_date desc);


-- ============================================================
-- 7. 三大法人大盤彙總（TWSE BFI82U）
-- ============================================================
create table if not exists public.three_institutionals (
  trade_date  date not null,
  investor    text not null,           -- '外資','投信','自營商'
  buy_amount  numeric(20,2),
  sell_amount numeric(20,2),
  net_amount  numeric(20,2),
  raw         jsonb,
  updated_at  timestamptz not null default now(),
  primary key (trade_date, investor)
);


-- ============================================================
-- 8. 景氣燈號（國發會 NDC leading）
-- ============================================================
create table if not exists public.business_cycle (
  month       date primary key,        -- 月份第一日
  score       int,
  signal      text,                    -- '紅燈','黃紅燈','綠燈','黃藍燈','藍燈'
  color_hex   text,
  raw         jsonb,
  fetched_at  timestamptz not null default now()
);


-- ============================================================
-- 9. 新聞條目（Reddit / PTT / UDN / Google News / 自選股新聞）
-- ============================================================
create table if not exists public.news_items (
  id            bigint generated by default as identity primary key,
  source        text not null,        -- 'reddit','ptt','udn','gnews','portnews'
  category      text,                 -- subreddit name / 'gossiping' / 'finance' / stock_code
  ext_id        text,                 -- reddit.id / ptt url hash / rss guid
  title         text,
  title_zh      text,                 -- 若為英文來源，儲存已翻譯的繁中標題
  url           text,
  summary       text,
  published_at  timestamptz,
  author        text,
  score         int,                  -- reddit upvotes / ptt 推文數
  raw           jsonb,
  fetched_at    timestamptz not null default now(),
  unique (source, ext_id)
);
create index if not exists idx_news_items_source    on public.news_items(source);
create index if not exists idx_news_items_published on public.news_items(published_at desc);
create index if not exists idx_news_items_category  on public.news_items(category);


-- ============================================================
-- 10. 推薦個股每日快照（取代 localStorage smtm_rec_hist）
-- ============================================================
create table if not exists public.recommendation_snapshots (
  trade_date    date primary key,
  picks         jsonb not null,       -- [{code,name,score,bullish,netBuy,volUp,tags,pe,yld,...}, ...]
  generated_at  timestamptz not null default now(),
  params        jsonb                 -- 可選：記錄當次篩選參數
);


-- ============================================================
-- 11. 翻譯快取（Google Translate gtx）— 省流量與 rate limit
-- ============================================================
create table if not exists public.translations (
  source_hash   text primary key,     -- sha256(sl||'|'||tl||'|'||text)
  source_lang   text,
  target_lang   text,
  source_text   text,
  translated    text,
  provider      text default 'gtx',
  created_at    timestamptz not null default now()
);
create index if not exists idx_translations_provider on public.translations(provider);


-- ============================================================
-- 12. 財經日曆（原本 hardcode 在 JS 裡，遷到 DB 方便維運）
-- ============================================================
create table if not exists public.fin_calendar (
  id          bigint generated by default as identity primary key,
  event_date  date not null,
  name        text not null,
  category    text,                   -- 'data','mkt','earn','cbc','other'
  note        text,
  url         text,
  country     text default 'TW',
  created_at  timestamptz not null default now(),
  unique (event_date, name)
);
create index if not exists idx_fin_calendar_date on public.fin_calendar(event_date);


-- ============================================================
-- 13. 統一啟用 RLS + 建立 policies
--     - 讀：anon + authenticated 皆可（公用快取）
--     - 寫：僅 authenticated（登入使用者可幫忙回寫快取）
-- ============================================================
do $$
declare
  tbl text;
  tbls text[] := array[
    'api_cache','market_indices','stock_daily','stock_quotes',
    'stock_fundamentals','institutional_flow','three_institutionals',
    'business_cycle','news_items','recommendation_snapshots',
    'translations','fin_calendar'
  ];
begin
  foreach tbl in array tbls loop
    execute format('alter table public.%I enable row level security', tbl);

    execute format('drop policy if exists "%s_select_all" on public.%I', tbl, tbl);
    execute format('drop policy if exists "%s_insert_auth" on public.%I', tbl, tbl);
    execute format('drop policy if exists "%s_update_auth" on public.%I', tbl, tbl);

    execute format(
      'create policy "%s_select_all" on public.%I for select to anon, authenticated using (true)',
      tbl, tbl
    );
    execute format(
      'create policy "%s_insert_auth" on public.%I for insert to authenticated with check (true)',
      tbl, tbl
    );
    execute format(
      'create policy "%s_update_auth" on public.%I for update to authenticated using (true) with check (true)',
      tbl, tbl
    );
    -- 不提供 DELETE policy；如需清理由管理員於 SQL Editor 手動處理
  end loop;
end$$;


-- ============================================================
-- 14. 便利視圖：近 30 天個股均價 / 每日更新摘要（範例）
-- ============================================================
create or replace view public.v_stock_latest as
  select distinct on (stock_code)
         stock_code, trade_date, close, change_pct, volume
    from public.stock_daily
   order by stock_code, trade_date desc;

create or replace view public.v_news_latest as
  select source, category, title, coalesce(title_zh, title) as title_display,
         url, published_at, score
    from public.news_items
   order by published_at desc nulls last
   limit 500;


-- ============================================================
-- 15. 驗證
--   select table_name from information_schema.tables
--    where table_schema='public' order by table_name;
--   select tablename, policyname, cmd from pg_policies
--    where schemaname='public' order by tablename, cmd;
-- ============================================================
